### ISSUE TITLE
失败重连问题

### ISSUE THREAD

**Issue by Tyeeee** [hezhubo/AndroidScreenLive#1]
哥们儿，咱这个demo里面如果断网模拟推流失败，然后再联网我发现底层没办法自动重连呢。 返回的write状态依旧还是0，无法自动变成1。针对这一点你有什么好的建议吗？或者说后期有加上这部分功能的计划？

**Comment by hezhubo** [comment]
从现在的设计上底层只是移植rtmpdump库，只做rtmp的推流。自动重连在上层做就好了，工程代码中write失败会有onError回调，在这个回调里面设计重连业务逻辑就好。demo中是连续write失败200次就停止推流。

**Comment by Tyeeee** [comment]
好的，谢谢你，我研究一下看看。
