### ISSUE TITLE
请教一些功能实现

### ISSUE THREAD

**Issue by Haleclipse** [hezhubo/AndroidScreenLive#2]
我想实现推流中实时修改系统声音和麦克风声音的音量大小比例
https://github.com/hezhubo/AndroidScreenLive/blob/5c96594f646050317e4afc1d71b543790d80208f/app/src/main/java/com/hezb/live/TestFilterHelper.kt#L38
这里的音频过滤器似乎是调整混音之后的音量大小吧
是否应该在混音之前就调整捕获到的音频才可以

**Comment by hezhubo** [comment]
> 我想实现推流中实时修改系统声音和麦克风声音的音量大小比例
> 
> https://github.com/hezhubo/AndroidScreenLive/blob/5c96594f646050317e4afc1d71b543790d80208f/app/src/main/java/com/hezb/live/TestFilterHelper.kt#L38
> 
> 
> 这里的音频过滤器似乎是调整混音之后的音量大小吧
> 是否应该在混音之前就调整捕获到的音频才可以

可以的，但我代码中写死了固定值，你可以把它调整成一个可动态修改的参数
https://github.com/hezhubo/AndroidScreenLive/blob/5c96594f646050317e4afc1d71b543790d80208f/lib-live/src/main/java/com/hezb/lib/live/core/AudioCapturerThread.kt#L156

**Comment by Haleclipse** [comment]
> > 我想实现推流中实时修改系统声音和麦克风声音的音量大小比例
> > 
> > https://github.com/hezhubo/AndroidScreenLive/blob/5c96594f646050317e4afc1d71b543790d80208f/app/src/main/java/com/hezb/live/TestFilterHelper.kt#L38
> > 
> > 
> > 这里的音频过滤器似乎是调整混音之后的音量大小吧
> > 是否应该在混音之前就调整捕获到的音频才可以
> 
> 可以的，但我代码中写死了固定值，你可以把它调整成一个可动态修改的参数
> https://github.com/hezhubo/AndroidScreenLive/blob/5c96594f646050317e4afc1d71b543790d80208f/lib-live/src/main/java/com/hezb/lib/live/core/AudioCapturerThread.kt#L156

oh好的非常感谢，原来是这个
